[General]
DOWNLOAD_FILE = url=https://raw.githubusercontent.com/2252031668/openclash-two-subscriptions/71b435baaea99b413c118f6864b8efcf8f2189ab/config/openclash-base.yaml, path=/etc/openclash/config/openclash-base.yaml, force=true
CONFIG_FILE = /etc/openclash/config/openclash-base.yaml
RESTART = true

[Overwrite]
ruby_map_edit "$CONFIG_FILE" "['proxy-providers']" "cheap" "['url']" "$EN_KEY1"
ruby_map_edit "$CONFIG_FILE" "['proxy-providers']" "premium_ai" "['url']" "$EN_KEY2"
